version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mathjs
    versions:
    - 9.0.0
    - 9.1.0
    - 9.2.0
    - 9.3.0
  - dependency-name: jasmine
    versions:
    - 3.6.4
  - dependency-name: ejs
    versions:
    - 3.1.5
  - dependency-name: lodash
    versions:
    - 4.17.20
